#execution: sequential
tmdb:
  quick_match: true
library:
  directory: film
  rules:
  # - expression: missing
  #   modification: grayscale
  #   property: link
  # - expression: exists
  #   modification: none # border
  #   property: link
  #   color: yellow
  - expression: contains
    property: torrent
    value: hun
    case_sensitive: false
    color: red
    modification: border
