name: Library clean up and P2P task
delay: 5
priority: 1
steps:

  - name: Collect Jellyfin favorites
    module: jellyfin
    action: get
    input:
      query:
        parentLibrary: Trending
        isFavorite: true
        allUsers: true
  - name: Add Jackett data
    module: jackett
    action: enrich
    input: previous
    config:
      search_preference: ['HDR 1080p', '1080p', 'HDR 2160p', 2160p']
  - name: Add to Transmission
    module: transmission
    action: put
    input: previous