name: Library clean up and P2P task
delay: 15  # minutes
priority: 1
steps:

  - name: Collect Jellyfin favorites
    module: jellyfin
    action: get
    input:
      query:
        parentLibrary: "Trending Filmek"
        isFavorite: true
        allUsers: true
  - name: Add Jackett data
    module: jackett
    action: enrich
    input: previous
    config:
      must_match: true
  - name: Add to Transmission
    module: transmission
    action: put
    input: previous
