name: Remove itom from Library if already in Jellyfin
delay: 60
priority: 20
steps:
  - name: Load from library
    module: library
    action: get
  - name: Filter out Jellyfin not existing
    module: jellyfin
    action: common
    input:
      query:
        parentLibrary: Trending
        isInverse: true
      data: previous
  - name: Delete from library
    module: library
    action: remove
    input: previous