name: TMDb to Jellyfin
delay: 60
priority: 1
steps:
  - name: Collect from TMDB
    module: tmdb
    action: get
  - name: Extend with Jackett data
    module: jackett
    action: enrich
    input: previous
    config:
      must_match: true
  - name: Filter out Jellyfin existing
    module: jellyfin
    action: unique
    input:
      query:
        parentLibrary: Trending
        isInverse: true
      data: previous
  - name: Export to library
    module: library
    action: put
    input: previous
