name: Build

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh
      - name: Run build
        run: ./.github/scripts/python-build.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-packages
          path: dist/
          retention-days: 15