name: Publish

on:
  workflow_run:
    workflows: ["Test", "Build"]
    types: [completed]
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-packages
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-packages
          path: dist/
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh
      - name: Build and push Docker image
        run: |
          ./.github/scripts/docker-build.sh
          VERSION=$(cat VERSION)
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker push cineflow:$VERSION
            docker push cineflow:latest
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            docker push cineflow:dev-$VERSION
          fi